name = "srnyx's Modpack"
author = "srnyx"
version = "3.0.0-qol"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1250b0022d5cef751a43244c9632ebaef26abe37a89e1c42dabeb9ae04bb2a28"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1", "1.18.2"]
