name = "srnyx's Modpack"
author = "srnyx"
version = "3.0.0-qol"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "21af190976635c318ad29af2c0eb7018342b5e85f9bd4ead0bbda7d27b974479"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
