name = "srnyx's Modpack"
author = "srnyx"
version = "3.0.1-qol"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "907dff6aa9242ca75de24de1db4da88274bca7073a86b5e2f08583a39fcd2946"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1", "1.18.2"]
