name = "srnyx's Modpack"
author = "srnyx"
version = "3.0.1-qol"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c9595cb8712a0b30993fd63ba16667be00147dfdcf35e2bc51f62ce0a1f5d6c"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1", "1.18.2"]
