name = "srnyx's Modpack"
author = "srnyx"
version = "3.0.0-qol"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e2a5e18610aac436e6769ae217fb10c856392fea8cd11018754a4cba5d2f96cc"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1", "1.18.2"]
