name = "srnyx's Modpack"
author = "srnyx"
version = "3.0.0-qol"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2571dd3e27d189614ecb4a36594520a0220acf235bedd3fbe7d79bcaa90c43e5"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1", "1.18.2"]
