name = "srnyx's Modpack"
author = "srnyx"
version = "3.0.0-qol"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "57188b8a63bb840d99ac40e956b65b7057a83c9fdf66475e41b29b19e9a85881"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1", "1.18.2"]
