name = "srnyx's Modpack"
author = "srnyx"
version = "4.0.0-oo"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea21f64ff0a913e108d2e097fa5992562cfd98db82f745297a59ec88823f0f8b"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
