name = "srnyx's Modpack QOL"
author = "srnyx"
version = "2.2.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0029ec83c1a0df51f3f0cd45b5029c9c0987d7340fa2ef9fb78dfe92efe033f7"

[versions]
fabric = "0.13.3"
minecraft = "1.17.1"
