
[general]

	[general.general]
		streamer_mode = false
		modcore_warning = true
		gui_scale = true
		network_messages = true

	[general.online_status]
		show_essential_indicator_on_tab = true
		show_essential_indicator_on_nametags = true

	[general.experience]
		alternate_character_customizer = false
		essential_full = true

	[general.friends]
		invite_friends = true

[privacy]

	[privacy.general]
		display_current_server = true
		friend_privacy_settings = 0

[notifications]

	[notifications.general]
		disable_all_notifications = false
		message_sound = true
		online_friend_alert = true
		message_notifications = true
		group_message_notifications = true

[quality_of_life]

	[quality_of_life.zoom]
		smooth_zoom_animation = false
		toggle_to_zoom = false
		smooth_camera_when_zoomed = true

