name = "srnyx's Modpack"
author = "srnyx"
version = "3.0.1-oo"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "795a92d35eff4662f80bb5b9a7734873a3d44a3cb2c8e920abeffe1836b4b095"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1", "1.18.2"]
