name = "srnyx's Modpack"
author = "srnyx"
version = "3.0.0-oo"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72ebb6ead4dc12164ae9c7e591231d541d4d7c87cc8a001898452be0628e98bf"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
