name = "srnyx's Modpack"
author = "srnyx"
version = "3.0.0-oo"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb4dc8ab81089c98bd189df2e39726da1e279b1e4b7529603e08670438b11afb"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1", "1.18.2"]
