name = "srnyx's Modpack"
author = "srnyx"
version = "3.0.0-oo"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80623bfe5dace74fdbd47f1ef4558794a32059d196c8ab073d173e009b656712"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
