name = "srnyx's Modpack QOL 1.17.1"
author = "srnyx"
version = "2.2.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3ab8a6c805f836d0e4d179f06efee856c321e0282055caa4dbe5bccffcb026d"

[versions]
fabric = "0.13.3"
minecraft = "1.17.1"
