name: OO 1.18.x Builds

on:
  push:
    branches:
      - main
    paths:
      - 'OO/1.18.*/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build modpack
      run: ./Tools/backend/actions.sh
      with:
        version: OO/1.18.*
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: OO 1.18.x
        path: "OO/1.18.*/srnyx's Modpack-*-oo.*"
