name: OO 1.17.x Builds

on:
  push:
    branches:
      - main
    paths:
      - 'OO/1.17.*/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build modpack
      run: |
        "cd OO/1.17.*"
        "../../Tools/backend/packwiz.exe modrinth export"
        "../../Tools/backend/packwiz.exe curseforge export"
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: OO 1.17.x
        path: "OO/1.17.*/srnyx's Modpack-*-oo.*"
