name: QOL 1.19.x Builds

on:
  push:
    branches:
      - main
    paths:
      - 'QOL/1.19.*/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set environment variable
      env:
        version: QOL/1.19.*
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build modpack
      run: ./Tools/backend/actions.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: QOL 1.19.x
        path: "QOL/1.19.*/srnyx's Modpack-*-qol.*"
